const SOURCES = {
  latestmodapks: {
    name: 'LatestModAPKs',
    baseUrl: 'https://www.latestmodapks.com',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.post-grid .post',
      title: '.post-title a',
      icon: '.post-thumb img',
      link: '.post-title a',
      version: '.post-meta .version',
      size: '.post-meta .size',
    },
    rateLimit: 1500,
  },
  getmodsapk: {
    name: 'GetModsAPK',
    baseUrl: 'https://getmodsapk.com',
    searchUrl: '/?s={query}',
    selectors: {
      list: '.post-item',
      title: '.post-title a',
      icon: '.post-thumb img',
      link: '.post-title a',
      version: '.version',
      size: '.filesize',
    },
    rateLimit: 1500,
  },
  play5: {
    name: '5Play',
    baseUrl: 'https://5play.org/en',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.app-item',
      title: '.app-name',
      icon: '.app-icon img',
      link: 'a.app-link',
      version: '.app-version',
      size: '.app-size',
    },
    rateLimit: 2000,
  },
  an1: {
    name: 'AN1',
    baseUrl: 'https://an1.com',
    searchUrl: '/search/?q={query}',
    selectors: {
      list: '.app-item',
      title: '.app-name a',
      icon: '.app-icon img',
      link: '.app-name a',
      version: '.app-version',
      size: '.app-size',
    },
    rateLimit: 1500,
  },
  modyolo: {
    name: 'ModYolo',
    baseUrl: 'https://modyolo.com',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.post-item',
      title: '.post-title a',
      icon: '.post-thumb img',
      link: '.post-title a',
      version: '.version',
      size: '.size',
    },
    rateLimit: 1500,
  },
  liteapks: {
    name: 'LiteAPKs',
    baseUrl: 'https://liteapks.com',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.post-item',
      title: '.post-title a',
      icon: '.post-thumb img',
      link: '.post-title a',
      version: '.version',
      size: '.size',
    },
    rateLimit: 1500,
  },
  modsmaniac: {
    name: 'ModsManiac',
    baseUrl: 'https://modsmaniac.com',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.post',
      title: '.post-title a',
      icon: '.post-thumb img',
      link: '.post-title a',
      version: '.version',
      size: '.filesize',
    },
    rateLimit: 1500,
  },
  modzmania: {
    name: 'ModzMania',
    baseUrl: 'https://modzmania.com',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.game-item',
      title: '.game-title a',
      icon: '.game-thumb img',
      link: '.game-title a',
      version: '.version',
      size: '.size',
    },
    rateLimit: 1500,
  },
  nullsgg: {
    name: 'NullsGG',
    baseUrl: 'https://nulls.gg',
    searchUrl: '/search?q={query}',
    selectors: {
      list: '.server-item',
      title: '.server-name',
      icon: '.server-icon img',
      link: 'a.server-link',
      version: '.server-version',
      size: '.server-size',
    },
    rateLimit: 2000,
  },
  gamekillerapp: {
    name: 'GameKillerApp',
    baseUrl: 'https://gamekillerapp.com',
    searchUrl: '/?s={query}',
    selectors: {
      list: '.post',
      title: '.entry-title a',
      icon: '.post-thumbnail img',
      link: '.entry-title a',
      version: '.version',
      size: '.size',
    },
    rateLimit: 1500,
  },
  play5app: {
    name: '5Play.app',
    baseUrl: 'https://5play.app',
    searchUrl: '/en/search?q={query}',
    selectors: {
      list: '.app-item',
      title: '.app-name',
      icon: '.app-icon img',
      link: 'a.app-link',
      version: '.app-version',
      size: '.app-size',
    },
    rateLimit: 2000,
  },
};

const GAME_SOURCE_MAPPINGS = {
  'brawl stars': ['nullsgg', 'latestmodapks', 'getmodsapk', 'an1', 'play5'],
  'clash royale': ['nullsgg', 'latestmodapks', 'an1'],
  'clash of clans': ['nullsgg', 'getmodsapk', 'modyolo'],
  'boom beach': ['nullsgg'],
  'hay day': ['nullsgg'],
};

const SOURCE_ORDER = [
  'happymod', 'latestmodapks', 'getmodsapk', 'play5', 'an1',
  'modyolo', 'liteapks', 'modsmaniac', 'modzmania',
  'nullsgg', 'gamekillerapp', 'play5app',
];

module.exports = { SOURCES, GAME_SOURCE_MAPPINGS, SOURCE_ORDER };
